import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {
  ChakraProvider,
  Container,
  GridItem,
  VStack,
  Box,
  Grid,
  Flex,
  Heading,
} from "@chakra-ui/react";
import Sidebar from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <header>
        <meta charSet="utf-8" />
        <meta name="description" content={metadata.description || ""} />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </header>
      <body className={inter.className}>
        <ChakraProvider>
          <Grid
            templateRows="80px 1fr auto"
            templateColumns="200px 1fr"
            height="100dvh"
            width="100%"
          >
            <GridItem
              style={{ backgroundColor: "tomato" }}
              colSpan={3}
              rowSpan={1}
            >
              <Flex paddingX={5} paddingY={3}>
                <Heading as="h1" size="2xl" textColor="whitesmoke">
                  Calculadora de finanzas
                </Heading>
              </Flex>
            </GridItem>
            <GridItem rowSpan={3} padding={5} bg="white" boxShadow="lg">
              <Sidebar />
            </GridItem>
            <GridItem colSpan={1} rowSpan={1}>
              <main>{children}</main>
            </GridItem>
            <GridItem rowSpan={1} colSpan={2}>
              <footer style={{ backgroundColor: "green" }}>Footer</footer>
            </GridItem>
          </Grid>
        </ChakraProvider>
      </body>
    </html>
  );
}
